// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mr_ccc_gibbs
List mr_ccc_gibbs(const arma::mat& X, const arma::mat& Z, const arma::mat& Y, const arma::mat& G, const arma::mat& H, const arma::mat& V, int n_iter, int burn_in, int thin, double a_sigma, double b_sigma, double a_rho, double b_rho, double nu1, double gG, double gV, double gH, double gZ, double gBeta, double ridge, int init_gamma, double init_scale, bool verbose, bool legacy_latent_prior);
RcppExport SEXP _MRCCC_mr_ccc_gibbs(SEXP XSEXP, SEXP ZSEXP, SEXP YSEXP, SEXP GSEXP, SEXP HSEXP, SEXP VSEXP, SEXP n_iterSEXP, SEXP burn_inSEXP, SEXP thinSEXP, SEXP a_sigmaSEXP, SEXP b_sigmaSEXP, SEXP a_rhoSEXP, SEXP b_rhoSEXP, SEXP nu1SEXP, SEXP gGSEXP, SEXP gVSEXP, SEXP gHSEXP, SEXP gZSEXP, SEXP gBetaSEXP, SEXP ridgeSEXP, SEXP init_gammaSEXP, SEXP init_scaleSEXP, SEXP verboseSEXP, SEXP legacy_latent_priorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type burn_in(burn_inSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< double >::type a_sigma(a_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type b_sigma(b_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type a_rho(a_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type b_rho(b_rhoSEXP);
    Rcpp::traits::input_parameter< double >::type nu1(nu1SEXP);
    Rcpp::traits::input_parameter< double >::type gG(gGSEXP);
    Rcpp::traits::input_parameter< double >::type gV(gVSEXP);
    Rcpp::traits::input_parameter< double >::type gH(gHSEXP);
    Rcpp::traits::input_parameter< double >::type gZ(gZSEXP);
    Rcpp::traits::input_parameter< double >::type gBeta(gBetaSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    Rcpp::traits::input_parameter< int >::type init_gamma(init_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type init_scale(init_scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type legacy_latent_prior(legacy_latent_priorSEXP);
    rcpp_result_gen = Rcpp::wrap(mr_ccc_gibbs(X, Z, Y, G, H, V, n_iter, burn_in, thin, a_sigma, b_sigma, a_rho, b_rho, nu1, gG, gV, gH, gZ, gBeta, ridge, init_gamma, init_scale, verbose, legacy_latent_prior));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MRCCC_mr_ccc_gibbs", (DL_FUNC) &_MRCCC_mr_ccc_gibbs, 24},
    {NULL, NULL, 0}
};

RcppExport void R_init_MRCCC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
